package JCTCLTv;

import javax.swing.*;

public class GUI extends Listing{
    private JPanel mainPanel;
    private JPanel l1;
    private JPanel l1ch;
    private JPanel l1prog;
    private JPanel l1pp1;
    private JPanel l1pp2;
    private JPanel l1pp3;
    private JPanel l1pp4;
    private JPanel l1pp5;
    private JPanel l1p1e;
    private JPanel l1p1i;
    private JLabel l1p1l;
    private JLabel l1chl;
    private JLabel l1p2l;
    private JPanel l1p2e;
    private JPanel l1p2i;
    private JLabel l1p3l;
    private JPanel l1p3i;
    private JPanel l1p3e;
    private JLabel l1p4l;
    private JPanel l1p4i;
    private JPanel l1p4e;
    private JLabel l1p5l;
    private JPanel l1p5i;
    private JPanel l1p5e;
    private JPanel l2;
    private JPanel l2ch;
    private JLabel l2chl;
    private JPanel l2prog;
    private JPanel l2pp1;
    private JLabel l2p1l;
    private JPanel l2p1i;
    private JPanel l2p1e;
    private JPanel l2pp2;
    private JLabel l2p2l;
    private JPanel l2p2i;
    private JPanel l2p2e;
    private JPanel l2pp3;
    private JLabel l2p3l;
    private JPanel l2p3e;
    private JPanel l2p3i;
    private JPanel l2pp4;
    private JLabel l2p4l;
    private JPanel l2p4i;
    private JPanel l2p4e;
    private JPanel l2pp5;
    private JLabel l2p5l;
    private JPanel l2p5i;
    private JPanel l2p5e;
    private JPanel top;
    private JPanel l3;
    private JPanel l3ch;
    private JLabel l3chl;
    private JPanel l3prog;
    private JPanel l3pp1;
    private JLabel l3p1l;
    private JPanel l3p1i;
    private JPanel l3p1e;
    private JPanel l3pp2;
    private JLabel l3p2l;
    private JPanel l3p2i;
    private JPanel l3p2e;
    private JPanel l3pp3;
    private JLabel l3p3l;
    private JPanel l3p3i;
    private JPanel l3p3e;
    private JPanel l3pp4;
    private JLabel l3p4l;
    private JPanel l3p4i;
    private JPanel l3p4e;
    private JPanel l3pp5;
    private JLabel l3p5l;
    private JPanel l3p5i;
    private JPanel l3p5e;
    private JPanel l4;
    private JPanel l5;
    private JPanel l6;
    private JPanel l7;
    private JPanel l4ch;
    private JLabel l4chl;
    private JPanel l4prog;
    private JPanel l4pp1;
    private JLabel l4p1l;
    private JPanel l4p1i;
    private JPanel l4p1e;
    private JPanel l4pp2;
    private JLabel l4p2l;
    private JPanel l4p2i;
    private JPanel l4p2e;
    private JPanel l4pp3;
    private JLabel l4p3l;
    private JPanel l4p3i;
    private JPanel l4p3e;
    private JPanel l4pp4;
    private JLabel l4p4l;
    private JPanel l4p4i;
    private JPanel l4p4e;
    private JPanel l4pp5;
    private JLabel l4p5l;
    private JPanel l4p5i;
    private JPanel l4p5e;
    private JPanel l5ch;
    private JLabel l5chl;
    private JPanel l5prog;
    private JPanel l5pp1;
    private JLabel l5p1l;
    private JPanel l5p1i;
    private JPanel l5p1e;
    private JPanel l5pp2;
    private JLabel l5p2l;
    private JPanel l5p2i;
    private JPanel l5p2e;
    private JPanel l5pp3;
    private JLabel l5p3l;
    private JPanel l5p3i;
    private JPanel l5p3e;
    private JPanel l5pp4;
    private JLabel l5p4l;
    private JPanel l5p4i;
    private JPanel l5p4e;
    private JPanel l5pp5;
    private JLabel l5p5l;
    private JPanel l5p5i;
    private JPanel l5p5e;
    private JPanel l6ch;
    private JLabel l6chl;
    private JPanel l6prog;
    private JPanel l6pp1;
    private JLabel l6p1l;
    private JPanel l6p1i;
    private JPanel l6p1e;
    private JPanel l6pp2;
    private JLabel l6p2l;
    private JPanel l6p2i;
    private JPanel l6p2e;
    private JPanel l6pp3;
    private JLabel l6p3l;
    private JPanel l6p3i;
    private JPanel l6p3e;
    private JPanel l6pp4;
    private JLabel l6p4l;
    private JPanel l6p4i;
    private JPanel l6p4e;
    private JPanel l6pp5;
    private JLabel l6p5l;
    private JPanel l6p5i;
    private JPanel l6p5e;
    private JPanel l7ch;
    private JLabel l7chl;
    private JPanel l7prog;
    private JPanel l7pp1;
    private JLabel l7p1l;
    private JPanel l7p1i;
    private JPanel l7p1e;
    private JPanel l7pp2;
    private JLabel l7p2l;
    private JPanel l7p2i;
    private JPanel l7p2e;
    private JPanel l7pp3;
    private JLabel l7p3l;
    private JPanel l7p3i;
    private JPanel l7p3e;
    private JPanel l7pp4;
    private JLabel l7p4l;
    private JPanel l7p4i;
    private JPanel l7p4e;
    private JPanel l7pp5;
    private JLabel l7p5l;
    private JPanel l7p5e;
    private JPanel l7p5i;
    private JPanel channels;
    private JPanel progs;
    private JPanel chanNum;
    private JPanel display;
    private JLabel time;
    private JLabel date;
    private JLabel day;
    private JPanel datetime;
    private JLabel jctclhead;
    private JPanel mainHead;
    private JPanel header;
    private JPanel header2;
    private JPanel list;
    private JScrollPane scroll2;
    private JScrollPane scroll3;

    private JFrame frame = new JFrame("JCTCL Cable Tv");
    public GUI(){

        l1p2l.setText(ch1P2.progName);

        l1chl.setText(ch1.getChNumber()+" - "+ch1.getChName());
        l2chl.setText(ch2.getChNumber()+" - "+ch2.getChName());
        l3chl.setText(ch3.getChNumber()+" - "+ch3.getChName());
        l4chl.setText(ch4.getChNumber()+" - "+ch4.getChName());
        l5chl.setText(ch5.getChNumber()+" - "+ch5.getChName());
        l6chl.setText(ch6.getChNumber()+" - "+ch6.getChName());
        l7chl.setText(ch7.getChNumber()+" - "+ch7.getChName());        

        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setUndecorated(true);
        frame.add(mainPanel);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);

    }

    public static void main(String[] args) {
        GUI gui = new GUI();
    }

}
